#!/bin/bash

export DOCKERTAG="jsola/verilog-tools:latest"
if [[ "$(docker images -q $DOCKERTAG 2> /dev/null)" == "" ]]; then
    echo "Docker image not detected, pulling image... "
    docker pull $DOCKERTAG 

fi

pushd $(dirname $0) &>/dev/null
REPOROOT=$(git rev-parse --show-toplevel)
CONTAINER_NAME=$(basename `git rev-parse --show-toplevel`)
popd &>/dev/null

if [[ "$(docker ps -f name=$CONTAINER_NAME | sed -n '1!p')" == "" ]]; then 
    echo "Creating container ..."
    docker run -w $REPOROOT --user $(id -u $(whoami)) -i -t -d -v $REPOROOT:$REPOROOT --name=$CONTAINER_NAME $DOCKERTAG > /dev/null
fi

docker exec -t $CONTAINER_NAME bash -c "verilator $*"

